# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='song',
            new_name='song_name',
        ),
        migrations.AddField(
            model_name='songs',
            name='lyrics',
            field=models.TextField(null=True),
        ),
    ]
