# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20170131_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='album',
        ),
        migrations.AddField(
            model_name='songs',
            name='lyrics_link',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
